#!/busybox/sh
set -xe

PROJECT=$PWD

mkdir -p /tmp

cat > /tmp/Dockerfile <<EOF
FROM python:3 as builder
COPY . /project
WORKDIR /project
# Install poetry
RUN ["pip", "install", "poetry>=1.0.0b1"]
# Export locks
RUN poetry export -o /tmp/requirements.txt -f requirements.txt $POETRY_EXPORT_ARGS
# Build wheels
RUN poetry build --format=wheel
RUN cp dist/* /tmp

# This is the real container
FROM python:3-slim

COPY --from=builder /tmp /tmp
RUN pip install --no-cache-dir --disable-pip-version-check -r /tmp/requirements.txt /tmp/*.whl

EOF

if [ -e /kaniko/executor ]; then
    /kaniko/executor --dockerfile /tmp/Dockerfile --context dir://$PROJECT ${KANIKO_ARGS:---no-push}
else
    docker build -f /tmp/Dockerfile $DOCKER_ARGS $PROJECT
fi
